create or replace force editionable view samqa.ar_invoice_v (
    invoice_number,
    invoice_date,
    invoice_due_date,
    status_code,
    status,
    invoice_posted_date,
    invoice_id,
    entrp_id,
    employer_name,
    acc_id,
    acc_num,
    account_type,
    invoice_term,
    start_date,
    end_date,
    coverage_period,
    comments,
    auto_pay,
    billing_name,
    billing_address,
    billing_city,
    billing_zip,
    billing_state,
    billing_attn,
    payment_method,
    invoice_status,
    invoice_reason,
    division_code,
    refund_amount,
    invoice_amount,
    pending_amount,
    paid_amount,
    void_amount,
    entity_id,
    entity_type,
    plan_type,
    rate_plan_id,
    charged_to,
    approved_date
) as
    select
        invoice_number,
        invoice_date,
        invoice_due_date
    --   ,  INVOICE_FREQUENCY
        ,
        status                                               status_code,
        decode(status, 'POSTED', 'Paid', 'Outstanding')      status,
        invoice_posted_date,
        invoice_id,
        decode(entity_type, 'EMPLOYER', entity_id)           entrp_id,
        pc_entrp.get_entrp_name(entity_id)                   employer_name,
        acc_id,
        acc_num,
        pc_account.get_account_type(acc_id)                  account_type,
        pc_lookups.get_meaning(invoice_term, 'PAYMENT_TERM') invoice_term,
        start_date,
        end_date,
        to_char(start_date, 'MM/DD/YYYY')
        || '-'
        || to_char(end_date, 'MM/DD/YYYY')                   coverage_period,
        comments,
        auto_pay,
        billing_name,
        billing_address,
        billing_city,
        billing_zip,
        billing_state,
        billing_attn,
        payment_method,
        status                                               invoice_status,
        invoice_reason,
        division_code,
        refund_amount,
        invoice_amount,
        nvl(pending_amount, 0)                               pending_amount,
        nvl(paid_amount, 0)                                  paid_amount,
        nvl(void_amount, 0)                                  void_amount,
        entity_id,
        entity_type,
        plan_type,
        rate_plan_id,
        charged_to, -- added by Jaggi #11484,
        approved_date
    from
        ar_invoice;


-- sqlcl_snapshot {"hash":"be9752947f3e2821029f2ee9a1fbe485361e44e5","type":"VIEW","name":"AR_INVOICE_V","schemaName":"SAMQA","sxml":""}