create or replace force editionable view samqa.crm_contacts_v (
    first_name,
    last_name,
    id,
    salutation,
    title,
    department,
    "ACCOUNT NAME",
    email,
    "Mobile Phone",
    "Office Phone",
    "Home Phone",
    "Other Phone",
    "Fax",
    "Primary Address Street",
    "Primary Address City",
    "Primary Address State",
    "Primary Address Postal Code",
    "Primary Address Country",
    "Alternate Address Street",
    "Alternate Address City",
    "Alternate Address State",
    "Alternate Address Postal Code",
    "Alternate Address Country",
    "Description",
    "Birthdate",
    "Lead Source",
    "Campaign ID",
    "Do Not Call",
    "Reports To ID",
    "Assistant",
    "Assistant Phone",
    "Assigned User Name",
    "Assigned User ID",
    "Date Created",
    "Date Modified",
    "Modified By ID",
    "Created By ID",
    "Deleted"
) as
    select distinct
        a.first_name,
        a.last_name,
        a.contact_id                     id,
        null                             salutation,
        a.title,
        null                             department,
        b.name                           "ACCOUNT NAME",
        a.email,
        null                             "Mobile Phone",
        a.phone                          "Office Phone",
        null                             "Home Phone",
        null                             "Other Phone",
        a.fax                            "Fax",
        null                             "Primary Address Street",
        null                             "Primary Address City",
        null                             "Primary Address State",
        null                             "Primary Address Postal Code",
        null                             "Primary Address Country",
        null                             "Alternate Address Street",
        null                             "Alternate Address City",
        null                             "Alternate Address State",
        null                             "Alternate Address Postal Code",
        null                             "Alternate Address Country",
        null                             "Description",
        null                             "Birthdate",
        null                             "Lead Source",
        null                             "Campaign ID",
        decode(a.status, 'A', 0, 'I', 1) "Do Not Call",
        null                             "Reports To ID",
        null                             "Assistant",
        null                             "Assistant Phone",
        'admin'                          "Assigned User Name",
        null                             "Assigned User ID",
        null                             "Date Created",
        null                             "Date Modified",
        null                             "Modified By ID",
        null                             "Created By ID",
        0                                "Deleted"
    from
        contact    a,
        enterprise b
    where
        replace(
            replace(a.entity_id, '-'),
            ' '
        ) = replace(
            replace(b.entrp_code, '-'),
            ' '
        );


-- sqlcl_snapshot {"hash":"67cf38ea1fa63f9b61175f433a16d429bdcc705b","type":"VIEW","name":"CRM_CONTACTS_V","schemaName":"SAMQA","sxml":""}