create or replace force editionable view samqa.employer_enrollment_pdf_v (
    enrollment_id,
    name,
    ein_number,
    address,
    city,
    state,
    zip,
    contact_name,
    phone,
    email,
    fee_plan_type,
    plan_code,
    broker_lic,
    er_contribution_frequency,
    ee_contribution_frequency,
    er_contribution_flag,
    ee_contribution_flag,
    setup_fee_paid_by,
    maint_fee_paid_by,
    management_account_user_name,
    enrollment_account_user_name,
    management_account_password,
    enrollment_account_password,
    password_question,
    password_answer,
    entrp_id,
    acc_num,
    enrollment_status,
    error_message,
    creation_date,
    created_by,
    last_update_date,
    last_updated_by,
    lang_perf,
    peo_ein,
    file_name
) as
    select
        enrollment_id,
        name,
        ein_number,
        address,
        city,
        state,
        zip,
        contact_name,
        phone,
        email,
        fee_plan_type,
        plan_code,
        broker_lic,
        er_contribution_frequency,
        ee_contribution_frequency,
        er_contribution_flag,
        ee_contribution_flag,
        setup_fee_paid_by,
        maint_fee_paid_by,
        management_account_user_name,
        enrollment_account_user_name,
        management_account_password,
        enrollment_account_password,
        password_question,
        password_answer,
        entrp_id,
        acc_num,
        enrollment_status,
        error_message,
        to_char(creation_date, 'MM/DD/YYYY') creation_date,
        created_by,
        last_update_date,
        last_updated_by,
        lang_perf,
        peo_ein,
        acc_num                              file_name
    from
        employer_online_enrollment
    where
        enrollment_status = 'S';


-- sqlcl_snapshot {"hash":"a3cacf6fc0e3fca6a5fd1629285e1b03fd8ff784","type":"VIEW","name":"EMPLOYER_ENROLLMENT_PDF_V","schemaName":"SAMQA","sxml":""}